use std::collections::HashMap;
use std::fs::File;
use std::hash::{Hash, Hasher};
use std::io::{Read, Seek, Write};
use std::path::Path;

use log::{debug, trace};
use zip::CompressionMethod;
use zip::read::ZipArchive;
use zip::write::{SimpleFileOptions, ZipWriter};

use super::content_types::{ContentTypes, ContentTypesBuilder};
use super::error::{Error, Result};
use super::properties::{AppProperties, CoreProperties};
use super::relationships::{Relationships, RelationshipsBuilder, TargetMode, rel_types};

// ---------------------------------------------------------------------------
// PartName
// ---------------------------------------------------------------------------

/// A validated, normalized OPC part name.
///
/// Part names always start with '/' and are compared case-insensitively per OPC §5.
#[derive(Debug, Clone)]
pub struct PartName(String);

/// Decode percent-encoded UTF-8 sequences (e.g., `%C3%A1` → `á`).
fn decode_percent_encoding(input: &str) -> String {
    let bytes = input.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let (Some(hi), Some(lo)) = (hex_digit(bytes[i + 1]), hex_digit(bytes[i + 2])) {
                decoded.push(hi << 4 | lo);
                i += 3;
                continue;
            }
        }
        decoded.push(bytes[i]);
        i += 1;
    }
    String::from_utf8(decoded).unwrap_or_else(|_| input.to_string())
}

fn hex_digit(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

impl PartName {
    /// Validate and create a new PartName per OPC part naming rules.
    /// Percent-encoded sequences are decoded before validation (tolerant parsing
    /// for files generated by LibreOffice which incorrectly percent-encodes non-ASCII).
    pub fn new(name: &str) -> Result<Self> {
        // Decode percent-encoding if present (tolerant of non-spec-compliant producers)
        let name = if name.contains('%') {
            decode_percent_encoding(name)
        } else {
            name.to_string()
        };

        // Must start with '/'
        if !name.starts_with('/') {
            return Err(Error::InvalidPartName(format!("must start with '/': {name}")));
        }
        // Must not end with '/'
        if name.len() > 1 && name.ends_with('/') {
            return Err(Error::InvalidPartName(format!("must not end with '/': {name}")));
        }
        // No empty segments (//)
        if name.contains("//") {
            return Err(Error::InvalidPartName(format!("empty segment (//): {name}")));
        }
        // No dot segments
        for segment in name.split('/').skip(1) {
            if segment == "." || segment == ".." {
                return Err(Error::InvalidPartName(format!("dot segment not allowed: {name}")));
            }
            // Segments must not end with '.'
            if segment.ends_with('.') {
                return Err(Error::InvalidPartName(format!("segment ends with dot: {name}")));
            }
        }
        // No query/fragment
        if name.contains('?') || name.contains('#') {
            return Err(Error::InvalidPartName(format!("query/fragment not allowed: {name}")));
        }
        // No backslashes
        if name.contains('\\') {
            return Err(Error::InvalidPartName(format!("backslash not allowed: {name}")));
        }

        Ok(Self(name))
    }

    /// Return the part name as a string slice (always starts with `/`).
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Extract the file extension (without leading dot), if any.
    pub fn extension(&self) -> Option<&str> {
        let filename = self.filename();
        filename.rfind('.').map(|i| &filename[i + 1..])
    }

    /// The directory portion, e.g. "/word/" for "/word/document.xml".
    pub fn directory(&self) -> &str {
        match self.0.rfind('/') {
            Some(i) => &self.0[..=i],
            None => "/",
        }
    }

    /// The filename portion, e.g. "document.xml" for "/word/document.xml".
    pub fn filename(&self) -> &str {
        match self.0.rfind('/') {
            Some(i) => &self.0[i + 1..],
            None => &self.0,
        }
    }

    /// Compute the path to this part's relationships file.
    /// e.g. "/word/document.xml" -> "/word/_rels/document.xml.rels"
    pub fn rels_path(&self) -> String {
        let dir = self.directory();
        let file = self.filename();
        format!("{dir}_rels/{file}.rels")
    }

    /// Resolve a relative URI against this part name's directory.
    pub fn resolve_relative(&self, relative: &str) -> Result<PartName> {
        if relative.starts_with('/') {
            // Absolute path
            return PartName::new(relative);
        }

        let base = self.directory();
        let combined = format!("{base}{relative}");

        // Normalize path by resolving .. and .
        let normalized = normalize_path(&combined);
        PartName::new(&normalized)
    }
}

/// Case-insensitive equality per OPC spec §5.
impl PartialEq for PartName {
    fn eq(&self, other: &Self) -> bool {
        self.0.eq_ignore_ascii_case(&other.0)
    }
}

impl Eq for PartName {}

/// Case-insensitive hashing to match case-insensitive equality.
impl Hash for PartName {
    fn hash<H: Hasher>(&self, state: &mut H) {
        for byte in self.0.bytes() {
            state.write_u8(byte.to_ascii_lowercase());
        }
    }
}

impl std::fmt::Display for PartName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Normalize a path by resolving `.` and `..` segments.
fn normalize_path(path: &str) -> String {
    let mut segments: Vec<&str> = Vec::new();
    for segment in path.split('/') {
        match segment {
            "." | "" => {
                // Skip empty (from leading slash or //) and current-dir refs
                if segments.is_empty() {
                    segments.push(""); // preserve leading slash
                }
            },
            ".." => {
                // Go up one level, but don't go above root
                if segments.len() > 1 {
                    segments.pop();
                }
            },
            s => segments.push(s),
        }
    }
    if segments.len() == 1 && segments[0].is_empty() {
        return "/".to_string();
    }
    segments.join("/")
}

// ---------------------------------------------------------------------------
// OpcReader
// ---------------------------------------------------------------------------

/// Reader for OPC (Open Packaging Conventions) packages (ZIP-based).
pub struct OpcReader<R: Read + Seek> {
    archive: ZipArchive<R>,
    entries: ZipEntryIndex,
    content_types: ContentTypes,
    package_rels: Relationships,
}

impl OpcReader<File> {
    /// Open an OPC package from a file path.
    pub fn open(path: impl AsRef<Path>) -> Result<Self> {
        let file = File::open(path)?;
        Self::new(file)
    }
}

#[cfg(feature = "mmap")]
impl OpcReader<std::io::Cursor<memmap2::Mmap>> {
    /// Open an OPC package using memory-mapped I/O for better performance on large files.
    ///
    /// # Safety
    /// Uses `unsafe` for memory mapping. The file must not be modified while mapped.
    pub fn open_mmap(path: impl AsRef<Path>) -> Result<Self> {
        let file = File::open(path)?;
        let mmap = unsafe { memmap2::Mmap::map(&file)? };
        debug!("OPC package opened via mmap ({} bytes)", mmap.len());
        Self::new(std::io::Cursor::new(mmap))
    }
}

impl<R: Read + Seek> OpcReader<R> {
    /// Create an OPC reader from any `Read + Seek` source.
    pub fn new(reader: R) -> Result<Self> {
        let mut archive = open_zip_rejecting_duplicates(reader)?;
        debug!("OPC package opened, {} entries", archive.len());
        let entries = ZipEntryIndex::new(&archive);

        // Eagerly parse [Content_Types].xml
        let ct_data = read_zip_entry(&mut archive, &entries, "[Content_Types].xml")?;
        let content_types = ContentTypes::parse(&ct_data)?;

        // Eagerly parse _rels/.rels
        let rels_data = read_zip_entry(&mut archive, &entries, "_rels/.rels").unwrap_or_default();
        let package_rels = if rels_data.is_empty() {
            Relationships::empty()
        } else {
            Relationships::parse(&rels_data)?
        };

        Ok(Self {
            archive,
            entries,
            content_types,
            package_rels,
        })
    }

    /// Return the parsed `[Content_Types].xml` table.
    pub fn content_types(&self) -> &ContentTypes {
        &self.content_types
    }

    /// Fail unless the package's primary part carries one of `expected`
    /// content types.
    ///
    /// Opening an XLSX as a DOCX used to succeed and produce an empty
    /// document — a caller who guessed the format wrong got silence rather
    /// than "this is not a WordprocessingML package". The corpus has 16
    /// files of exactly this shape (ODT stored as `.docx`, XLSB stored as
    /// `.xls`, and so on).
    pub fn verify_main_content_type(&self, expected: &[&str], label: &str) -> Result<()> {
        let Ok(main) = self.main_document_part() else {
            // No primary part at all is a different (already reported) error.
            return Ok(());
        };
        let Some(found) = self.content_types.overrides().get(&main) else {
            // No override entry — nothing to contradict.
            return Ok(());
        };
        if expected.iter().any(|e| found == e) {
            return Ok(());
        }
        Err(Error::FormatMismatch {
            found: found.clone(),
            expected: label.to_string(),
        })
    }

    /// Return the package-level relationships from `_rels/.rels`.
    pub fn package_rels(&self) -> &Relationships {
        &self.package_rels
    }

    /// Read a part's raw bytes.
    /// XML parts with non-UTF-8 encoding declarations are automatically transcoded to UTF-8.
    pub fn read_part(&mut self, name: &PartName) -> Result<Vec<u8>> {
        let zip_path = &name.as_str()[1..]; // strip leading /
        let data = read_zip_entry(&mut self.archive, &self.entries, zip_path)?;
        trace!("read_part '{}' ({} bytes)", name, data.len());

        // Transcode non-UTF-8 XML to UTF-8 (handles ISO-8859-1, Windows-1252, etc.)
        if name.as_str().ends_with(".xml") || name.as_str().ends_with(".rels") {
            if let Some(utf8_data) = super::xml::ensure_utf8(&data) {
                trace!("read_part '{}': transcoded to UTF-8", name);
                return Ok(utf8_data);
            }
        }
        Ok(data)
    }

    /// Read and parse the relationships for a given part.
    pub fn read_rels_for(&mut self, part: &PartName) -> Result<Relationships> {
        let rels_zip_path = part.rels_path();
        let zip_path = &rels_zip_path[1..]; // strip leading /
        match read_zip_entry(&mut self.archive, &self.entries, zip_path) {
            Ok(data) => {
                trace!("read_rels_for '{}' ({} bytes)", part, data.len());
                Relationships::parse(&data)
            },
            Err(Error::Zip(zip::result::ZipError::FileNotFound)) => {
                trace!("read_rels_for '{}': no rels file", part);
                Ok(Relationships::empty())
            },
            Err(Error::MissingPart(_)) => {
                trace!("read_rels_for '{}': no rels file", part);
                Ok(Relationships::empty())
            },
            Err(e) => Err(e),
        }
    }

    /// Find the main document part via the officeDocument relationship.
    /// Falls back to scanning `[Content_Types].xml` overrides when `_rels/.rels` is
    /// missing or corrupted.
    pub fn main_document_part(&self) -> Result<PartName> {
        // Primary: use the officeDocument relationship from _rels/.rels
        if let Some(rel) = self.package_rels.first_by_type(rel_types::OFFICE_DOCUMENT) {
            let target = if rel.target.starts_with('/') {
                rel.target.clone()
            } else {
                format!("/{}", rel.target)
            };
            return PartName::new(&target);
        }

        // Fallback: scan [Content_Types].xml overrides for a main document content type
        const MAIN_CONTENT_TYPES: &[&str] = &[
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml",
            "application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml",
        ];
        for (part_name, ct) in self.content_types.overrides() {
            if MAIN_CONTENT_TYPES.iter().any(|&expected| ct == expected) {
                debug!(
                    "main_document_part: fallback to Content_Types override '{}' ({})",
                    part_name, ct
                );
                return Ok(part_name.clone());
            }
        }

        Err(Error::RelationshipNotFound("officeDocument relationship not found".to_string()))
    }

    /// List all part names in the package (excluding special OPC files).
    pub fn part_names(&self) -> Vec<PartName> {
        self.archive
            .file_names()
            .filter_map(|name| {
                // Normalize backslash separators (Windows-created ZIPs)
                let name = name.replace('\\', "/");
                // Skip directories
                if name.ends_with('/') {
                    return None;
                }
                // Skip [Content_Types].xml
                if name.eq_ignore_ascii_case("[Content_Types].xml") {
                    return None;
                }
                // Skip .rels files in _rels directories
                if name.contains("_rels/") {
                    return None;
                }
                let part_name = format!("/{name}");
                PartName::new(&part_name).ok()
            })
            .collect()
    }

    /// Check if a part exists in the package.
    pub fn has_part(&self, name: &PartName) -> bool {
        let zip_path = &name.as_str()[1..];
        self.archive.index_for_name(zip_path).is_some() || self.entries.lookup(zip_path).is_some()
    }
}

/// Case-folded, separator-normalised entry name → index, built once per
/// archive.
///
/// The exact-name lookup is the zip crate's own hash map, but a name that
/// misses it — a `[Content_Types].xml` in another case, a Windows-written
/// `_rels\.rels`, or simply an optional part that is not there — used to be
/// resolved by scanning every entry and allocating a normalised copy of its
/// name. Part lookups happen once per slide, sheet, header, image and
/// relationship, and the XLSX loader *probes* for optional parts per sheet,
/// so package open was quadratic in the number of parts: 8,000 one-cell
/// sheets took 56 s. This index makes the miss as cheap as the hit.
pub(crate) struct ZipEntryIndex {
    by_normalized: HashMap<String, usize>,
}

impl ZipEntryIndex {
    pub(crate) fn new<R: Read + Seek>(archive: &ZipArchive<R>) -> Self {
        let mut by_normalized = HashMap::with_capacity(archive.len());
        for name in archive.file_names() {
            let Some(index) = archive.index_for_name(name) else {
                continue;
            };
            // Two names that normalise to the same key keep the lower
            // index, which is what the scan they replace returned.
            by_normalized
                .entry(Self::normalize(name))
                .and_modify(|existing: &mut usize| *existing = (*existing).min(index))
                .or_insert(index);
        }
        Self { by_normalized }
    }

    /// Index of the entry matching `name` case-insensitively, with `\` and
    /// `/` treated alike.
    pub(crate) fn lookup(&self, name: &str) -> Option<usize> {
        self.by_normalized.get(&Self::normalize(name)).copied()
    }

    fn normalize(name: &str) -> String {
        let mut key = String::with_capacity(name.len());
        for b in name.chars() {
            key.push(if b == '\\' {
                '/'
            } else {
                b.to_ascii_lowercase()
            });
        }
        key
    }
}

/// Read a ZIP entry by name, returning its bytes.
/// Falls back to case-insensitive and backslash-normalized lookup if exact match fails.
/// Read the "total number of entries in the central directory" field from a
/// ZIP's End of Central Directory record.
///
/// Returns `None` when the record cannot be located or the archive uses the
/// ZIP64 sentinel, in which case the caller simply skips the duplicate check
/// rather than guessing. The field is the only way to see duplicates at all:
/// the zip crate keys its entries by name, so two records with the same name
/// collapse into one before any caller can notice.
fn central_directory_entry_count<R: Read + Seek>(reader: &mut R) -> Result<Option<usize>> {
    const EOCD_SIG: [u8; 4] = [b'P', b'K', 5, 6];
    // The EOCD is at most 22 bytes plus a 64 KiB comment.
    const MAX_SCAN: u64 = 22 + 0xFFFF;

    let len = reader.seek(std::io::SeekFrom::End(0))?;
    if len < 22 {
        return Ok(None);
    }
    let scan = MAX_SCAN.min(len);
    reader.seek(std::io::SeekFrom::End(-(scan as i64)))?;
    let mut buf = vec![0u8; scan as usize];
    reader.read_exact(&mut buf)?;

    // Scan backwards for the signature; the last match is the real EOCD.
    let Some(pos) = buf
        .windows(4)
        .rposition(|w| w == EOCD_SIG)
        .filter(|&p| p + 12 <= buf.len())
    else {
        return Ok(None);
    };
    let total = u16::from_le_bytes([buf[pos + 10], buf[pos + 11]]);
    // 0xFFFF is the ZIP64 sentinel: the real count lives elsewhere.
    if total == u16::MAX {
        return Ok(None);
    }
    Ok(Some(total as usize))
}

/// Open a ZIP archive, refusing one that holds two entries with the same
/// name.
///
/// Which of two same-named entries a reader returns is unspecified, so two
/// implementations reading the same bytes can see two different
/// documents. That is the shape of CVE-2025-31672 and of every "scanner
/// reads one copy, renderer reads the other" bypass. Whichever copy we
/// picked would be accidental, so the package is refused. The
/// central-directory record count is read *before* the zip crate sees the
/// reader, because the crate keys entries by name and collapses duplicates
/// before any caller can notice.
///
/// Every OOXML reader must open its archive through this — `OpcReader`
/// does, and so does the XLSX fast path, which bypasses `OpcReader` for
/// speed and for a while bypassed this check with it.
pub(crate) fn open_zip_rejecting_duplicates<R: Read + Seek>(
    mut reader: R,
) -> Result<ZipArchive<R>> {
    let declared_entries = central_directory_entry_count(&mut reader)?;
    reader.seek(std::io::SeekFrom::Start(0))?;
    let archive = ZipArchive::new(reader)?;
    if let Some(declared) = declared_entries {
        if declared > archive.len() {
            return Err(Error::DuplicatePart(format!(
                "{declared} central-directory entries collapse to {} unique names",
                archive.len()
            )));
        }
    }
    Ok(archive)
}

/// Maximum uncompressed size accepted for a single OPC part.
///
/// Real documents do not have half-gigabyte parts; a file that claims to
/// is either corrupt or a decompression bomb. Refusing it with an error is
/// the difference between a failed parse and an out-of-memory kill of the
/// host process — and every binding (Python, Go, C#, WASM) inherits that
/// difference.
pub const MAX_PART_SIZE: u64 = 512 * 1024 * 1024;

pub(crate) fn read_zip_entry<R: Read + Seek>(
    archive: &mut ZipArchive<R>,
    entries: &ZipEntryIndex,
    name: &str,
) -> Result<Vec<u8>> {
    // Exact match first, then the case-insensitive + backslash-normalised
    // index: `[Content_Types].xml` case variants and Windows-created ZIPs
    // that use backslash separators (e.g., `_rels\.rels`).
    let index = archive
        .index_for_name(name)
        .or_else(|| entries.lookup(name))
        .ok_or_else(|| Error::MissingPart(name.to_string()))?;
    let mut file = archive
        .by_index(index)
        .map_err(|_| Error::MissingPart(name.to_string()))?;

    // Reject decompression bombs before allocating for them. A ZIP entry
    // declares its uncompressed size in the central directory; a 2 MB
    // `.docx` whose `document.xml` claims to expand to 2 GiB is a
    // deliberate memory-exhaustion payload (the OOXML analogue of
    // CVE-2014-3574). The declared size is attacker-controlled, so it is
    // used only to refuse early — the read below is separately capped so a
    // lying header cannot get past it either.
    if file.size() > MAX_PART_SIZE {
        return Err(Error::DecompressionLimit {
            part: name.to_string(),
            limit: MAX_PART_SIZE,
        });
    }
    let mut buf = Vec::with_capacity((file.size() as usize).min(1 << 20));
    let mut capped = (&mut file).take(MAX_PART_SIZE + 1);
    match capped.read_to_end(&mut buf) {
        Ok(_) => {},
        Err(e)
            if e.kind() == std::io::ErrorKind::InvalidData
                && e.to_string().contains("checksum")
                && !buf.is_empty() =>
        {
            // CRC32 mismatch — the data was fully decompressed but the checksum
            // doesn't match. Accept the data anyway for tolerance of real-world
            // files with minor corruption (e.g., re-saved without recomputing CRC).
            trace!("read_zip_entry '{}': ignoring CRC mismatch", name);
        },
        Err(e) => return Err(e.into()),
    }
    if buf.len() as u64 > MAX_PART_SIZE {
        return Err(Error::DecompressionLimit {
            part: name.to_string(),
            limit: MAX_PART_SIZE,
        });
    }
    Ok(buf)
}

// ---------------------------------------------------------------------------
// OpcWriter
// ---------------------------------------------------------------------------

/// Writer for creating OPC packages (ZIP-based).
pub struct OpcWriter<W: Write + Seek> {
    writer: ZipWriter<W>,
    content_types: ContentTypesBuilder,
    package_rels: RelationshipsBuilder,
    part_rels: HashMap<String, RelationshipsBuilder>,
}

impl OpcWriter<File> {
    /// Create a new OPC package at the given file path.
    pub fn create(path: impl AsRef<Path>) -> Result<Self> {
        let file = File::create(path)?;
        Self::new(file)
    }
}

impl<W: Write + Seek> OpcWriter<W> {
    /// Create a new OPC package writer wrapping an arbitrary `Write + Seek` sink.
    pub fn new(writer: W) -> Result<Self> {
        Ok(Self {
            writer: ZipWriter::new(writer),
            content_types: ContentTypesBuilder::new(),
            package_rels: RelationshipsBuilder::new(),
            part_rels: HashMap::new(),
        })
    }

    /// Register a default `[Content_Types].xml` entry for a file
    /// extension. Use this for parts whose content type is uniform
    /// across the package (e.g. `ttf` for all embedded fonts, `png`
    /// for all raster images). Default + Override is legal OOXML;
    /// Override takes precedence at lookup time, so passing the same
    /// content type to both is redundant but safe.
    ///
    /// Validators (Office Open XML SDK) flag packages that ship many
    /// per-file overrides without a matching Default — emit defaults
    /// for known-uniform extensions to satisfy them.
    pub fn register_default_content_type(&mut self, extension: &str, content_type: &str) {
        self.content_types.add_default(extension, content_type);
    }

    /// Add a part to the package.
    pub fn add_part(&mut self, name: &PartName, content_type: &str, data: &[u8]) -> Result<()> {
        // Register content type override
        self.content_types.add_override(name.clone(), content_type);

        // Write to ZIP
        let zip_path = &name.as_str()[1..]; // strip leading /
        let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
        self.writer.start_file(zip_path, options)?;
        self.writer.write_all(data)?;
        Ok(())
    }

    /// Add a package-level relationship and return its rId.
    pub fn add_package_rel(&mut self, rel_type: &str, target: &str) -> String {
        self.package_rels.add(rel_type, target)
    }

    /// Add a part-level relationship and return its rId.
    pub fn add_part_rel(&mut self, source: &PartName, rel_type: &str, target: &str) -> String {
        self.part_rels
            .entry(source.as_str().to_string())
            .or_default()
            .add(rel_type, target)
    }

    /// Add a part-level relationship with an explicit target mode and return its rId.
    pub fn add_part_rel_with_mode(
        &mut self,
        source: &PartName,
        rel_type: &str,
        target: &str,
        target_mode: TargetMode,
    ) -> String {
        self.part_rels
            .entry(source.as_str().to_string())
            .or_default()
            .add_with_mode(rel_type, target, target_mode)
    }

    /// Set core properties (Dublin Core metadata) for the package.
    pub fn set_core_properties(&mut self, props: &CoreProperties) -> Result<()> {
        let data = props.serialize();
        let name = PartName::new("/docProps/core.xml")?;
        self.content_types.add_override(
            name.clone(),
            "application/vnd.openxmlformats-package.core-properties+xml",
        );
        let zip_path = &name.as_str()[1..];
        let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
        self.writer.start_file(zip_path, options)?;
        self.writer.write_all(&data)?;
        self.package_rels
            .add(rel_types::CORE_PROPERTIES, "docProps/core.xml");
        Ok(())
    }

    /// Set app/extended properties for the package.
    pub fn set_app_properties(&mut self, props: &AppProperties) -> Result<()> {
        let data = props.serialize();
        let name = PartName::new("/docProps/app.xml")?;
        self.content_types.add_override(
            name.clone(),
            "application/vnd.openxmlformats-officedocument.extended-properties+xml",
        );
        let zip_path = &name.as_str()[1..];
        let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
        self.writer.start_file(zip_path, options)?;
        self.writer.write_all(&data)?;
        self.package_rels
            .add(rel_types::EXTENDED_PROPERTIES, "docProps/app.xml");
        Ok(())
    }

    /// Finalize the OPC package: writes `[Content_Types].xml`, `_rels/.rels`,
    /// part-level `.rels` files, and closes the ZIP archive.
    pub fn finish(mut self) -> Result<W> {
        let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

        // Write part-level .rels files
        for (source_path, builder) in &self.part_rels {
            if builder.is_empty() {
                continue;
            }
            let source = PartName::new(source_path)?;
            let rels_path = source.rels_path();
            let zip_path = &rels_path[1..]; // strip leading /
            let data = builder.serialize();
            self.writer.start_file(zip_path, options)?;
            self.writer.write_all(&data)?;
        }

        // Write _rels/.rels
        let rels_data = self.package_rels.serialize();
        self.writer.start_file("_rels/.rels", options)?;
        self.writer.write_all(&rels_data)?;

        // Write [Content_Types].xml
        let ct_data = self.content_types.serialize();
        self.writer.start_file("[Content_Types].xml", options)?;
        self.writer.write_all(&ct_data)?;

        Ok(self.writer.finish()?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn archive_of(names: &[&str]) -> ZipArchive<std::io::Cursor<Vec<u8>>> {
        use std::io::Write;
        let mut zip = ZipWriter::new(std::io::Cursor::new(Vec::new()));
        for name in names {
            zip.start_file(*name, SimpleFileOptions::default()).unwrap();
            zip.write_all(b"x").unwrap();
        }
        ZipArchive::new(zip.finish().unwrap()).unwrap()
    }

    /// The index answers exactly what the per-call scan it replaced
    /// answered: case-insensitive, `\` and `/` alike, absent is `None`,
    /// and when two names collide the lower index wins as the scan did.
    #[test]
    fn test_entry_index_matches_case_and_separator_insensitively() {
        let archive = archive_of(&[
            "[Content_Types].xml",
            "_rels\\.rels",
            "xl/Worksheets/Sheet1.xml",
        ]);
        let index = ZipEntryIndex::new(&archive);
        assert_eq!(
            index.lookup("[content_types].XML"),
            archive.index_for_name("[Content_Types].xml")
        );
        assert_eq!(index.lookup("_rels/.rels"), archive.index_for_name("_rels\\.rels"));
        assert_eq!(
            index.lookup("xl\\worksheets\\sheet1.xml"),
            archive.index_for_name("xl/Worksheets/Sheet1.xml")
        );
        assert_eq!(index.lookup("xl/worksheets/sheet2.xml"), None);
    }

    #[test]
    fn test_entry_index_keeps_the_first_of_two_colliding_names() {
        let archive = archive_of(&["word/Document.xml", "word/document.xml"]);
        let index = ZipEntryIndex::new(&archive);
        assert_eq!(index.lookup("WORD/DOCUMENT.XML"), Some(0));
    }

    /// `has_part` and the `read_zip_entry` fallback rescanned every entry,
    /// allocating a normalised copy of each name, on every call. Probing
    /// each of N absent parts against N entries is the shape every loader
    /// has (one optional rels/drawing/comments part per sheet or slide);
    /// it must stay linear.
    #[test]
    fn test_absent_part_probes_do_not_rescan_the_archive() {
        let names: Vec<String> = (0..4000)
            .map(|i| format!("xl/worksheets/sheet{i}.xml"))
            .collect();
        let refs: Vec<&str> = names.iter().map(String::as_str).collect();
        let archive = archive_of(&refs);
        let entries = ZipEntryIndex::new(&archive);
        let started = std::time::Instant::now();
        let mut hits = 0;
        for i in 0..4000 {
            if entries
                .lookup(&format!("xl/worksheets/_rels/sheet{i}.xml.rels"))
                .is_some()
            {
                hits += 1;
            }
            if entries
                .lookup(&format!("XL/WORKSHEETS/SHEET{i}.XML"))
                .is_some()
            {
                hits += 1;
            }
        }
        assert_eq!(hits, 4000);
        assert!(
            started.elapsed() < std::time::Duration::from_secs(2),
            "8,000 lookups against 4,000 entries took {:?}",
            started.elapsed()
        );
    }

    #[test]
    fn test_valid_part_names() {
        assert!(PartName::new("/word/document.xml").is_ok());
        assert!(PartName::new("/xl/worksheets/sheet1.xml").is_ok());
        assert!(PartName::new("/docProps/core.xml").is_ok());
        assert!(PartName::new("/word/media/image1.png").is_ok());
    }

    #[test]
    fn test_invalid_part_names() {
        assert!(PartName::new("word/document.xml").is_err()); // no leading /
        assert!(PartName::new("/word/document.xml/").is_err()); // trailing /
        assert!(PartName::new("/word//document.xml").is_err()); // empty segment
        assert!(PartName::new("/word/./document.xml").is_err()); // dot segment
        assert!(PartName::new("/word/../document.xml").is_err()); // dotdot segment
        // Percent-encoding is now decoded tolerantly
        let pn = PartName::new("/word/my%20doc.xml").unwrap();
        assert_eq!(pn.as_str(), "/word/my doc.xml");
        assert!(PartName::new("/word/doc.xml?v=1").is_err()); // query string
    }

    #[test]
    fn test_part_name_case_insensitive_eq() {
        let a = PartName::new("/Word/Document.xml").unwrap();
        let b = PartName::new("/word/document.xml").unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn test_part_name_case_insensitive_hash() {
        use std::collections::HashSet;
        let mut set = HashSet::new();
        set.insert(PartName::new("/Word/Document.xml").unwrap());
        assert!(set.contains(&PartName::new("/word/document.xml").unwrap()));
    }

    #[test]
    fn test_part_name_components() {
        let pn = PartName::new("/word/document.xml").unwrap();
        assert_eq!(pn.directory(), "/word/");
        assert_eq!(pn.filename(), "document.xml");
        assert_eq!(pn.extension(), Some("xml"));
        assert_eq!(pn.rels_path(), "/word/_rels/document.xml.rels");
    }

    #[test]
    fn test_resolve_relative_simple() {
        let source = PartName::new("/word/document.xml").unwrap();
        let resolved = source.resolve_relative("media/image1.png").unwrap();
        assert_eq!(resolved.as_str(), "/word/media/image1.png");
    }

    #[test]
    fn test_resolve_relative_parent() {
        let source = PartName::new("/word/document.xml").unwrap();
        let resolved = source.resolve_relative("../docProps/core.xml").unwrap();
        assert_eq!(resolved.as_str(), "/docProps/core.xml");
    }

    #[test]
    fn test_resolve_relative_absolute() {
        let source = PartName::new("/word/document.xml").unwrap();
        let resolved = source.resolve_relative("/xl/workbook.xml").unwrap();
        assert_eq!(resolved.as_str(), "/xl/workbook.xml");
    }

    #[test]
    fn test_opc_round_trip() {
        use std::io::Cursor;

        let buf = Vec::new();
        let cursor = Cursor::new(buf);
        let mut writer = OpcWriter::new(cursor).unwrap();

        // Add a part
        let doc_name = PartName::new("/word/document.xml").unwrap();
        writer
            .add_part(
                &doc_name,
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml",
                b"<document/>",
            )
            .unwrap();
        writer.add_package_rel(rel_types::OFFICE_DOCUMENT, "word/document.xml");

        let result = writer.finish().unwrap();
        let data = result.into_inner();

        // Read it back
        let cursor = Cursor::new(data);
        let mut reader = OpcReader::new(cursor).unwrap();

        // Check content types
        let ct = reader.content_types().resolve(&doc_name);
        assert_eq!(
            ct,
            Some(
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"
            )
        );

        // Check package rels
        let main = reader.main_document_part().unwrap();
        assert_eq!(main.as_str(), "/word/document.xml");

        // Read part content
        let content = reader.read_part(&doc_name).unwrap();
        assert_eq!(content, b"<document/>");

        // Check part list
        let parts = reader.part_names();
        assert!(parts.iter().any(|p| p == &doc_name));
    }
}
