"""Type stubs for the office_oxide native extension module.

These stubs cover the public API exposed by the Rust ``_native`` module.
Every `path` argument accepts ``str`` or any ``os.PathLike[str]``.
"""

from os import PathLike
from types import TracebackType
from typing import Any, Literal

from typing_extensions import Self, TypeAlias

__version__: str

FormatName: TypeAlias = Literal["docx", "xlsx", "pptx", "doc", "xls", "ppt"]
_Path: TypeAlias = str | PathLike[str]
_CellValue: TypeAlias = str | bool | int | float | None

class OfficeOxideError(Exception):
    """Raised for any parse, IO, or conversion failure inside office_oxide."""

class Document:
    """A parsed Office document (read-only).

    Supports use as a context manager::

        with Document.open("report.docx") as doc:
            print(doc.plain_text())
    """

    @staticmethod
    def open(path: _Path, /) -> Document: ...
    @staticmethod
    def from_bytes(data: bytes, format: FormatName, /) -> Document: ...
    @property
    def format(self) -> FormatName: ...
    def format_name(self) -> FormatName: ...
    def plain_text(self) -> str: ...
    def to_markdown(self) -> str: ...
    def to_html(self) -> str: ...
    def to_ir(self) -> dict[str, Any]: ...
    def to_ir_json(self) -> str: ...
    def save_as(self, path: _Path, /) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool: ...

class EditableDocument:
    """An editable Office document (DOCX, XLSX, PPTX)."""

    @staticmethod
    def open(path: _Path, /) -> EditableDocument: ...
    def replace_text(self, find: str, replace: str, /) -> int: ...
    def set_cell(
        self, sheet_index: int, cell_ref: str, value: _CellValue, /
    ) -> None: ...
    def save(self, path: _Path, /) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool: ...

class XlsxWriter:
    """Builder for creating XLSX workbooks from scratch."""

    def __init__(self) -> None: ...
    def add_sheet(self, name: str) -> int: ...
    def set_cell(self, sheet: int, row: int, col: int, value: _CellValue) -> None: ...
    def set_cell_styled(
        self,
        sheet: int,
        row: int,
        col: int,
        value: _CellValue,
        bold: bool,
        bg_color: str | None = None,
    ) -> None: ...
    def merge_cells(
        self, sheet: int, row: int, col: int, row_span: int, col_span: int
    ) -> None: ...
    def set_column_width(self, sheet: int, col: int, width: float) -> None: ...
    def save(self, path: _Path) -> None: ...
    def to_bytes(self) -> bytes: ...

class PptxWriter:
    """Builder for creating PPTX presentations from scratch."""

    def __init__(self) -> None: ...
    def set_presentation_size(self, cx: int, cy: int) -> None: ...
    def add_slide(self) -> int: ...
    def set_slide_title(self, slide: int, title: str) -> None: ...
    def add_slide_text(self, slide: int, text: str) -> None: ...
    def add_slide_image(
        self,
        slide: int,
        data: bytes,
        format: str,
        x: int,
        y: int,
        cx: int,
        cy: int,
    ) -> None: ...
    def save(self, path: _Path) -> None: ...
    def to_bytes(self) -> bytes: ...

def extract_text(path: _Path, /) -> str: ...
def to_markdown(path: _Path, /) -> str: ...
def to_html(path: _Path, /) -> str: ...
def create_from_markdown(markdown: str, format: str, path: _Path, /) -> None: ...
def version() -> str: ...
